services:

  db:
    image: postgres:17 # pinning to 17, as 18 is not fully released and has a different data mount path.
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: devpassword
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - type: bind
        source: ./data/db/data
        target: /var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
