CREATE TABLE "fantasy_positions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE,
  "abbreviation" varchar UNIQUE,
  "external_fantasy_id" integer UNIQUE
);

CREATE TABLE "venues" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "external_fantasy_id" integer UNIQUE
);


CREATE TABLE "positions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE,
  "fantasy_position_id" integer REFERENCES fantasy_positions(id)
);

CREATE TABLE "players" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "dob" date,
  "team_id" integer,
  "external_fantasy_id" integer UNIQUE,
  "primary_fantasy_position_id" integer NOT NULL REFERENCES fantasy_positions(id),
  "secondary_fantasy_position_id" integer REFERENCES fantasy_positions(id)
);

CREATE TABLE "rounds" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "round" integer,
  "year" integer,
  "start" date,
  "end" date,
  UNIQUE (round, year)
);

CREATE TABLE "player_prices" (
  "player_id" integer NOT NULL,
  "round_id" integer NOT NULL,
  "price" integer,
  PRIMARY KEY (player_id,round_id)
);

CREATE TABLE "teams" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "short_name" varchar,
  "abbreviation" varchar,
  "external_fantasy_id" integer UNIQUE
);

CREATE TABLE "matches" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "round_id" integer NOT NULL,
  "venue_id" integer NOT NULL,
  "home_team_id" integer NOT NULL,
  "away_team_id" integer NOT NULL,
  "date" timestamptz,
  "external_fantasy_id" integer UNIQUE
);

CREATE TABLE "player_match_stats" (
  "player_id" integer NOT NULL,
  "match_id" integer NOT NULL,
  "team_id" integer NOT NULL,
  "fantasy_score" integer,
  "mp" integer,
  "t" integer,
  "ts" integer,
  "g" integer,
  "fg" integer,
  "ta" integer,
  "lb" integer,
  "lba" integer,
  "tck" integer,
  "tb" integer,
  "mt" integer,
  "ofh" integer,
  "ofg" integer,
  "er" integer,
  "ftf" integer,
  "mg" integer,
  "km" integer,
  "kd" integer,
  "pc" integer,
  "sb" integer,
  "so" integer,
  "tog" integer,
  "fdo" integer,
  "to" integer,
  "sai" integer,
  "efig" integer,
  PRIMARY KEY (player_id,match_id,team_id)
);

CREATE TABLE "match_stats" (
  "match_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "home_score" integer,
  "away_score" integer
);

CREATE TABLE "transfers" (
  "from_id" integer REFERENCES teams(id),
  "to_id" integer REFERENCES teams(id),
  "round_id" integer REFERENCES rounds(id),
  "player_id" integer REFERENCES players(id),
  PRIMARY KEY (from_id, to_id, round_id, player_id)
);

CREATE TABLE "prices" (
  -- A price entry indicates the price at the start of the round
  "player_id" integer NOT NULL REFERENCES players(id),
  "round_id" integer NOT NULL REFERENCES rounds(id),
  "break_even" integer,
  PRIMARY KEY (player_id, round_id)
);

ALTER TABLE "players" ADD CONSTRAINT "team_players" FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

ALTER TABLE "matches" ADD CONSTRAINT "round" FOREIGN KEY ("round_id") REFERENCES "rounds" ("id");

ALTER TABLE "matches" ADD CONSTRAINT "team_home_matches" FOREIGN KEY ("home_team_id") REFERENCES "teams" ("id");

ALTER TABLE "matches" ADD CONSTRAINT "team_away_matches" FOREIGN KEY ("away_team_id") REFERENCES "teams" ("id");

ALTER TABLE "matches" ADD CONSTRAINT "venue" FOREIGN KEY ("venue_id") REFERENCES "venues" ("id");

ALTER TABLE "player_match_stats" ADD CONSTRAINT "player_stats" FOREIGN KEY ("player_id") REFERENCES "players" ("id");

ALTER TABLE "player_match_stats" ADD CONSTRAINT "team_player_stats" FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

ALTER TABLE "player_match_stats" ADD CONSTRAINT "matches_player_stats" FOREIGN KEY ("match_id") REFERENCES "matches" ("id");

ALTER TABLE "match_stats" ADD CONSTRAINT "match_stats_match" FOREIGN KEY ("match_id") REFERENCES "matches" ("id");

CREATE OR REPLACE FUNCTION calculate_fantasy_score()
RETURNS TRIGGER AS $$
BEGIN
  NEW.fantasy_score :=
    -- Tries (8 points each)
    COALESCE(NEW.t, 0) * 8 +
    -- Goals/Conversions (2 points each)
    COALESCE(NEW.g, 0) * 2 +
    -- Field Goals (5 points each)
    COALESCE(NEW.fg, 0) * 5 +
    -- Try Assists (5 points each)
    COALESCE(NEW.ta, 0) * 5 +
    -- Line Breaks (4 points each)
    COALESCE(NEW.lb, 0) * 4 +
    -- Line Break Assists (2 points each)
    COALESCE(NEW.lba, 0) * 2 +
    -- Tackles (1 point each)
    COALESCE(NEW.tck, 0) * 1 +
    -- Tackle Breaks (2 points each)
    COALESCE(NEW.tb, 0) * 2 +
    -- Missed Tackles (-2 points each)
    COALESCE(NEW.mt, 0) * (-2) +
    -- Offloads to Hand (4 points each)
    COALESCE(NEW.ofh, 0) * 4 +
    -- Offloads to Ground (2 points each)
    COALESCE(NEW.ofg, 0) * 2 +
    -- Errors (-2 points each)
    COALESCE(NEW.er, 0) * (-2) +
    -- 40/20 or 20/40 kicks (4 points each)
    COALESCE(NEW.ftf, 0) * 4 +
    -- Metres Gained (divided by 10, rounded down)
    FLOOR(COALESCE(NEW.mg, 0) / 10.0) +
    -- Kick Metres (divided by 30, rounded down)
    FLOOR(COALESCE(NEW.km, 0) / 30.0) +
    -- Penalty Conceded (-2 points each)
    COALESCE(NEW.pc, 0) * (-2) +
    -- 6-again Infringement (-1 point each)
    COALESCE(NEW.sai, 0) * (-1) +
    -- Sin-Bin (-5 points each)
    COALESCE(NEW.sb, 0) * (-5) +
    -- Send-Off (-10 points each)
    COALESCE(NEW.so, 0) * (-10) +
    -- Try Saves (5 points each)
    COALESCE(NEW.ts, 0) * 5 +
    -- Kicks Defused (1 point each)
    COALESCE(NEW.kd, 0) * 1 +
    -- Forced Drop-outs (2 points each)
    COALESCE(NEW.fdo, 0) * 2 +
    -- Turnovers (4 points each)
    COALESCE(NEW.to, 0) * 4 +
    -- Escape In Goal (2 points each)
    COALESCE(NEW.efig, 0) * 2;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER calculate_fantasy_score_trigger
BEFORE UPDATE ON player_match_stats
FOR EACH ROW
EXECUTE FUNCTION calculate_fantasy_score();